name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust_version: ['stable', 'beta', 'nightly']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      if: startsWith(matrix.os, 'macOS')
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust_version }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
